### PR TITLE
✨ Introduces Python version

### PR DESCRIPTION
**Pull request by amarrerod**

### CODE REVIEW

**Comment by marklreyes** [comment]
@amarrerod Awesome! I'm guessing you are on the latest version of Python?

**Comment by amarrerod** [comment]
Yes I do, trying out the type hints! @marklreyes

**Comment by marklreyes** [comment]
@amarrerod if you could add update the README file to reflect Python usage as well, that'd be great. I'll then merge. Thanks again for collaborating. I'm glad you have fun with it.

**Comment by amarrerod** [comment]
Done! I just updated the README. Thank you so much for the codebase, it was really fun! @marklreyes

**Pull request merged**
